apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ default .Release.Namespace .Values.namespace | trunc 63 | trimSuffix "-" }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ .Chart.Name }}