apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ .Values.managedIdentity.name}}-mi
spec:
  type: 0
  ResourceID: {{ .Values.managedIdentity.id }}
  ClientID: {{ .Values.managedIdentity.clientId }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ .Values.managedIdentity.name}}
spec:
  AzureIdentity: "{{ .Values.managedIdentity.name}}-mi"
  Selector: "msi"
